name: helm-build-and-push
env:
  CHART_NAME: custom-generic
permissions:
  packages: write
  contents: read
on:
  push:
    branches:
      - main
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: helm lint
        run: |
          helm lint ${CHART_NAME}
  build-and-upload:
    needs: [lint]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: get chart tag
        run: |
          ls -la
          export CHART_TAG=$(cat "${CHART_NAME}/Chart.yaml" | grep -E '^version:' | awk '{print $2}')
      - name: helm login
        run: |
          echo ${{ secrets.GHCR_TOKEN }} | helm registry login ghcr.io -u $ --password-stdin
      - name: helm package
        run: |
          echo "image-tag: ${CHART_TAG}"
          helm package ${CHART_NAME} --version $CHART_TAG
      - name: helm push
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "image-tag: ${CHART_TAG}"
          OWNER_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          helm push $CHART_NAME-$CHART_TAG.tgz oci://ghcr.io/$OWNER_NAME
